name: campcatalyst
favicon: null
layout_spectrum: 0.19334879121743143
typography_spectrum: 0.21578413085080683
title: Camp Catalyst
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ca00ee'
    - '#0affe1'
    - '#f6c7d9'
    - '#e6636d'
  brandStrength: 0.5
  lightness: 0.5167543750721961
  saturation: 0.20610816730186343
  rhythmicContrast: 0.25
purpose: []
